version: "3.1"

services: 
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmExercise
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
    pgdata: {}